### ISSUE TITLE
category filter won't display hidden courses to teachers

### ISSUE THREAD

**Issue by rimacher** [CLAMP-IT/moodle-blocks_filtered_course_list#102]
Hi,

I found out what didn't work for us in #100 issue. The categories I tested were hidden and changing the visibility fixed it. Teachers should be able to see hidden courses and categories.

**Comment by kwiliarty** [comment]
Oh, that's very helpful. I will look into it soon. Thanks so much for following up.

**Comment by kwiliarty** [comment]
There are some complications here that require some thought. Here are the things I have thought of. Feel free to suggest other considerations:

- The core Moodle capability to see hidden courses is `moodle/course:viewhiddencourses`. Teachers have this capability by default and the Filtered Course List honors it (according to the details outlined below).
- The core Moodle capability to see hidden categories is `moodle/category:viewhiddencategories`. The Filtered Course List honors this capability, too, but it is important to understand that teachers do not have it. The capability applies only in a "System" context, not in a course context. For that reason it cannot even be granted to the core "Teacher" role. 
- The Filtered Course List will show a hidden course in a visible category to a user who has the `viewhiddencourses` capability. The course will display with dimmed text.
- The Filtered Course List will not show a hidden category to a user who does not have `viewhiddencategories`, BUT...
- The Filtered Course List WILL include any courses from hidden categories under the "Other courses" rubric if you have that option enabled and if the course would otherwise be visible to the user. A teacher, for instance, should see both hidden and visible courses, while a student should see only visible courses.

Are you seeing a different behavior? 

I can understand why you might want the Filtered Course List to show hidden categories to users who can see hidden courses. I have sometimes wished for the same, but it is not the standard interpretation of the Moodle capabilities and I am wary of departing from the path that Moodle has laid out here.

**Comment by rimacher** [comment]
I see. It's a shame it can't be done but at least I know why it happened.

**Comment by kwiliarty** [comment]
It's definitely reassuring to understand now what was going on. Thanks again for all the feedback.
