### ISSUE TITLE
Move sort types and vectors to filter scope

### ISSUE THREAD

**Issue by azito122** [CLAMP-IT/moodle-blocks_filtered_course_list#106]
I think it would make sense to have these settings be per-filter / per-rubric, rather than global. They could be added to the textarea config like so:
```
category   | collapsed | asc fullname   | 0 (top level)    | 0 (all descendants)
category   | exp       | desc startdate | 1                | 2 (generations)

**Comment by azito122** [comment]
And a second field of the same type for the secondary sort type/vector.

**Comment by kwiliarty** [comment]
While I can see how it makes sense in terms of filling out logical possibilities, I would be disinclined to do this from a practical perspective. Back when I introduced sorting I specifically opted not to include it at the filter level. It seems like a lot to add two additional fields to each filter when no one so far has asked for that level of granularity. In many cases it would probably be confusing to have different sort principles under different rubrics. I would not want to get rid of the site config setting, so the config lines would also need an option to use the system settings. Empty fields could serve that purpose, but it still makes the config busy. 

Instead of taking it down to the filter level we could add granularity at the block instance level. Instances do not currently have sort settings, but they easily could. Anyone who needed different sort principles could then apply them at that level. I would be open to a PR for that, if you're interested in working on it.

**Comment by kwiliarty** [comment]
I think this is inactive at this point, so I'm going to close it.
