### ISSUE TITLE
Downgrade Issue

### ISSUE THREAD

**Issue by laupow** [CLAMP-IT/moodle-blocks_filtered_course_list#34]
I believe what happened was I updated the plugin via web interface then deployed a previous codebase which didn't contain the updated plugin source so moodle ran downgrade commands which failed. 

But that's pretty clear from the error message too:

```
stderr: Default exception handler: Cannot downgrade block_filtered_course_list from 2015112700 to 2015010700. Debug: 
Error code: cannotdowngrade
* line 929 of /lib/upgradelib.php: downgrade_exception thrown
* line 424 of /lib/upgradelib.php: call to upgrade_plugins_blocks()
* line 1628 of /lib/upgradelib.php: call to upgrade_plugins()
* line 171 of /admin/cli/upgrade.php: call to upgrade_noncore()
stdout: !!! Cannot downgrade block_filtered_course_list from 2015112700 to 2015010700. !!!
!! 
Error code: cannotdowngrade !!
!! Stack trace: * line 929 of /lib/upgradelib.php: downgrade_exception thrown
* line 424 of /lib/upgradelib.php: call to upgrade_plugins_blocks()
* line 1628 of /lib/upgradelib.php: call to upgrade_plugins()
* line 171 of /admin/cli/upgrade.php: call to upgrade_noncore()
 !!
```

I could probably repeat it if needed.

**Comment by kwiliarty** [comment]
Yes, I think that would explain it. If you want to go back to the older version, you can remove the plugin through the web interface but leave the older version of the code in place. Moodle will automatically reinstall the older version, but you would lose your settings. Otherwise, you could put the code for the newer version back in. Let me know how it works out.

**Comment by laupow** [comment]
I'm not too familiar with the structure of Moodle plugins yet but since a `downgrade_exception` was thrown it tells me that Moodle is aware the plugin state is old and trying to adapt but runs into an error in doing so. 

So I guess I'm just curious if the ability to successfully downgrade a plugin is a feature typically available. I believe I've seen others "downgrade" without an exception but maybe that was a fluke?

**Comment by kwiliarty** [comment]
Moodle will always choke on plugin code that is older than the latest version registered on that installation. What you are seeing is standard Moodle behavior and has nothing to do with the Filtered course list in particular. There's a table in the database that keeps track of which version you have of any plugin. If Moodle finds newer code, it offers to upgrade, but if it finds older code, it throws the error you are seeing. There is not generally any way to downgrade cleanly. 

In some cases you can fake a downgrade by acting on the database directly, but this is risky. If there have been changes to settings and database structure between versions you will definitely mess things up. Plugins include code to migrate existing installations when necessary, but they only go forward. In the case of the Filtered course list we have definitely made changes that cannot be reversed after an upgrade. That said, if you remove the block through the web interface, but leave the code, Moodle will just reinstall the older code. Settings will be lost, but in the case of the Filtered course list that should not be terrible to recreate.

I'm going to close the ticket, because there's not really anything to be done from the perspective of this module, but I'm happy to continue the discussion if you have more questions.

Cheers!
