### ISSUE TITLE
Search courses

### ISSUE THREAD

**Issue by tluger** [CLAMP-IT/moodle-blocks_filtered_course_list#43]
Is there a way to enable an authenticated user to search for courses without seeing the "All courses" link and only show search results for those they have access to (enrolled, self-enrollment, and guest)?

**Comment by tluger** [comment]
We have access to the server files and are able to add or alter code to accomplish this.

**Comment by kwiliarty** [comment]
I'm working on #44 / #45 right now, but thinking about this question, too. I'm not quite sure what you are looking for, though. There is already an option to show or hide the "All courses" link, so that part is covered. As for the search, are you looking for a link to a page with search results, or is it that you'd like the block to show all those courses? If it's the latter, do you mean that you'd like the user to see all the courses that they _are_ enrolled in or that they _could_ enroll in? I would say that the block already does the former and that the latter would probably be a different project.

**Comment by kwiliarty** [comment]
P.S. If you are looking for a list of enrollable courses then maybe you could achieve that using something like the Configurable Reports plugin (https://moodle.org/plugins/block_configurable_reports) or Ad-hoc database queries plugin (https://moodle.org/plugins/report_customsql).

**Comment by kwiliarty** [comment]
I'm closing this as out of the scope of the module, but feel free to reopen if you think I've misunderstood the request.
