### ISSUE TITLE
Course naming templates

### ISSUE THREAD

**Issue by rimacher** [CLAMP-IT/moodle-blocks_filtered_course_list#64]
Hello,

It could be nice to have an option to add the course shortname next to it's fullname in the block.

Our users rely on the shortname to distinguish between same name courses.

**Comment by kwiliarty** [comment]
This strikes me as a good idea. I'm imagining a setting that lets an admin establish a template for the way a course is listed. I won't be able to get to it immediately, but it will be on my roadmap.

**Comment by kwiliarty** [comment]
@rimacher If you have the ability to add some custom CSS to your theme(s) you can achieve what you are looking for immediately with something like this:

```
.block_filtered_course_list ul a::after {
  content: " (" attr(title) ")";
}
```

This would work because the shortname is already being set as the `title` attribute for course links. Using CSS to set content is not a best practice because the content created this way will not get picked up by a screen reader. On the other hand, the same content is already available as the link title, so as a temporary workaround this might be just what you need. 

In the long run my goal would be to provide two settings that would allow an admin to create display text and title formats using tokens (such as FULLNAME and SHORTNAME). The CSS tweak I mention might help you fill the gap until that goal is implemented.

**Comment by rimacher** [comment]
@kwiliarty Thank you! it works nicely and will help us greatly.
