### ISSUE TITLE
Decode HTML entities

### ISSUE THREAD

**Issue by mackensen** [CLAMP-IT/moodle-blocks_filtered_course_list#88]
We have courses with ampersands in the full name and short name (they're stored encoded, as `&amp;`). They render correctly on the Moodle course page and course overview block but get double encoded on the Filtered Course List. See attached screenshot.
![dashboard](https://user-images.githubusercontent.com/553370/35066652-60be7c80-fb9f-11e7-9ad7-5ca995617e25.png)

**Comment by kwiliarty** [comment]
Thanks for reporting that. I have been able to recreate the problem, and I'll work to solve it soon.

**Comment by kwiliarty** [comment]
When the native Moodle tools display course full- and short-names they decode the HTML entities. I have not been doing that, but clearly I should. This is an issue not only for ampersands but for any stored HTML entities (for instance, `&uuml;`).

**Comment by theTrolleyProblem** [comment]
Hello there.

This issue was closed however I'm still encountering this issue in the most recent version as of writing this - version v4.4.2 (2021011501). Could there be any changes made since then (2018, which is 4 years ago) that may have made this issue reoccur? If so it would be awesome if it could be patched. If not, are there any recommendations as where I may check the source of the issue?

Thank you in advance.

![image](https://user-images.githubusercontent.com/80886357/160974339-9413ac12-6883-423a-82b2-511fd60ff58a.png)
